### ISSUE TITLE
Section B-3 not available

### ISSUE THREAD

**Issue by TonyAvjrStark** [opxdelwin/plan-sync#2]
![Screenshot_2023-09-17-11-38-04-04_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/opxdelwin/plan-sync/assets/140642262/f5bd1c81-1ade-4267-905c-431ed8b2b004)
![Uploading Screenshot_2023-09-17-11-38-07-80_e2d5b3f32b79de1d45acd1fad96fbb0f.jpg…]()

**Comment by opxdelwin** [comment]
Please go through contributing guidelines [here](https://github.com/opxdelwin/plan-sync/blob/main/CONTRIBUTING.md)

**Comment by opxdelwin** [comment]
@TonyAvjrStark closing this issue as the semester is over. Feel free to join us to prepare Plan Sync for Semester 2.
